routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\Api\GroupsController;
use App\Http\Controllers\Api\UsersController;
use App\Http\Controllers\Api\TimeTableController;
use App\Http\Controllers\Api\FacultyController;
use App\Http\Controllers\Api\TeachersController;
use App\Http\Controllers\Api\ScheduleController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('admin')->group(function () {

    Route::resource('groups', GroupsController::class);
    Route::resource('faculty', FacultyController::class);
    Route::get('/faculty/delete/{id}', [FacultyController::class, 'delete'])->name('faculty.delete');
    Route::get('/groupss/delete/{id}', [GroupsController::class, 'delete'])->name('groups.delete');

    Route::resource('users', UsersController::class);
    Route::get('/userss/delete/{id}', [UsersController::class, 'delete'])->name('users.delete');

    Route::resource('teachers', TeachersController::class);
    Route::get('/teachers/delete/{id}', [TeachersController::class, 'delete'])->name('teachers.delete');

    Route::resource('time_table', TimeTableController::class);
    Route::get('/time_tables/delete/{id}', [TimeTableController::class, 'delete'])->name('time_tables.delete');

    Route::resource('teacher_time_table', ScheduleController::class);
    Route::get('/teacher_time_tables/delete/{id}', [ScheduleController::class, 'delete'])->name('teacher_time_tables.delete');

});

app/Models/Faculty.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Faculty extends Model
{
    use HasFactory;
    public  function getFacultyGroup(){

        return $this->hasMany('App\Models\Group','faculty_id','id');
    }
}

app/Http/Controllers/Api/FacultyController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Faculty;
use Validator;

class FacultyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $name = Faculty::all();
        return view('back.faculty.index',compact('name'));
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('back.faculty.create');
       
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make(
            $request->all(),
            [
                'name' => 'required',
            ]
        );
        
        if ($validator->fails()) {
            return [
                'status' => false,
                'errors' => $validator->messages()
            ];
        }



        $name = new Faculty;
        $name->name = $request->name;
        $name->save();

        //dd($group);

        return redirect()->route('faculty.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $name = Faculty::findOrFail($id);
        
        return view('back.faculty.update',compact('name'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make(
            $request->all(),
            [
                'name' => 'required',
            ]
        );



        if($validator->fails()){
            return redirect()->route('faculty.index');
        }


        $name = Faculty::findOrFail($id);

        if($name == null){
            return redirect()->route('faculty.index');
        }else{

            $name->name = $request->name;
            $name->save();

            return redirect()->route('faculty.index');

        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function delete($id)
    {
        $name = Faculty::where('id',$id)->first();

        $name->forceDelete();

        return redirect()->route('faculty.index');
    }
}

resources/views/back/faculty/create.blade.php
@extends('back.layouts.master')
@section('content')


                        <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            
                            <div class="card-body">
                                <!-- Credit Card -->
                                <div id="pay-invoice">
                                    <div class="card-body">
                                        @if($errors->any())
                            <div class="alert alert-danger">
                                @foreach($errors->all() as $error)
                                {{$error}}
                                @endforeach

                            </div>
                            @endif
                                        <div class="card-title">
                                            <h3 class="text-center">Täze Fakultet</h3>
                                        </div>
                                        <hr>
                                        <form action="{{route('faculty.store')}}" method="POST" enctype="multipart/form-data">
                                           @csrf
                                             

                                            <div class="form-group">
                                                <label  class="control-label mb-1">Fakultetiň ady</label>
                                                <input  name="name" type="text" class="form-control" required >
                                            </div>
                                         
                                           
                                            <div class="text-center">
                                                <button id="payment-button" type="submit" class="btn  btn-success btn-lg">
                                                 Fakultet goşmak
                                                </button>
                                            </div>
                                        </form>
                                    </div>
                                </div>

                            </div>
                        </div> <!-- .card -->

                    </div><!--/.col-->
                  </div>
@endsection

resources/views/back/faculty/index.blade.php
@extends('back.layouts.master')
@section('content')
 <div class="content">
            <div class="animated fadeIn">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <a href="{{route('faculty.create')}}"><div class="btn btn-sm btn-success">+ Täze Fakultet</div></a>
                            </div>
                            <div class="table-stats order-table ov-h">
                                <table class="table ">
                                    <thead>
                                        <tr>
                                            
                                             <th>Fakultetiň ady</th>
                                             <th>Goşmaçalar</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        
                                        @foreach($name as $item)
                                        <tr>
                                             <td> {{ $item->name }} </td>
                                            
                                            
                                             
                                            <td>
                                                <span class="product">
                                                <a href="{{route('faculty.edit',$item->id)}}" title="Update" class="btn btn-sm btn-primary"><i class="fa fa-pencil-square"></i></a>
                                                 <a href="{{route('faculty.delete',$item->id)}}"  title="delete" class="btn btn-sm btn-danger"><i class="fa fa-times"></i></a>
                                                </span>
                                            </td>
                                        </tr>
                                        @endforeach

                                    </tbody>
                                </table>
                            </div> 
                        </div>
                    </div>
                   
                
               

                
                 
                


           

            

        </div>
    </div><!-- .animated -->
</div><!-- .content -->

@endsection

resources/views/back/faculty/update.blade.php
@extends('back.layouts.master')
@section('content')


                        <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            
                            <div class="card-body">
                                <!-- Credit Card -->
                                <div id="pay-invoice">
                                    <div class="card-body">
                                        @if($errors->any())
                            <div class="alert alert-danger">
                                @foreach($errors->all() as $error)
                                {{$error}}
                                @endforeach

                            </div>
                            @endif
                                        <div class="card-title">
                                            <h3 class="text-center">Fakulteti redaktirlemek</h3>
                                        </div>
                                        <hr>
                                        <form action="{{route('faculty.update',$name->id)}}" method="POST" enctype="multipart/form-data">
                                         @method('PUT') 
                                             @csrf

                                            <div class="form-group">
                                                <label  class="control-label mb-1">Fakultetiň ady</label>
                                                <input  name="name" value="{{$name->name}}" type="text" class="form-control" required >
                                            </div>
                                          
                                            <div class="text-center">
                                            <button id="payment-button" type="submit" class="btn  btn-success btn-lg">
                                                  Täzele
                                                </button>
                                            </div>
                                        </form>
                                    </div>
                                </div>

                            </div>
                        </div> <!-- .card -->

                    </div><!--/.col-->
                  </div>
@endsection