routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\Api\GroupsController;
use App\Http\Controllers\Api\UsersController;
use App\Http\Controllers\Api\TimeTableController;
use App\Http\Controllers\Api\FacultyController;
use App\Http\Controllers\Api\TeachersController;
use App\Http\Controllers\Api\ScheduleController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('admin')->group(function () {

    Route::resource('groups', GroupsController::class);
    Route::resource('faculty', FacultyController::class);
    Route::get('/faculty/delete/{id}', [FacultyController::class, 'delete'])->name('faculty.delete');
    Route::get('/groupss/delete/{id}', [GroupsController::class, 'delete'])->name('groups.delete');

    Route::resource('users', UsersController::class);
    Route::get('/userss/delete/{id}', [UsersController::class, 'delete'])->name('users.delete');

    Route::resource('teachers', TeachersController::class);
    Route::get('/teachers/delete/{id}', [TeachersController::class, 'delete'])->name('teachers.delete');

    Route::resource('time_table', TimeTableController::class);
    Route::get('/time_tables/delete/{id}', [TimeTableController::class, 'delete'])->name('time_tables.delete');

    Route::resource('teacher_time_table', ScheduleController::class);
    Route::get('/teacher_time_tables/delete/{id}', [ScheduleController::class, 'delete'])->name('teacher_time_tables.delete');

});

resources/views/back/teachersSchedule/create.blade.php
@extends('back.layouts.master')
@section('content')


                        <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            
                            <div class="card-body">
                                <!-- Credit Card -->
                                <div id="pay-invoice">
                                    <div class="card-body">
                                        @if($errors->any())
                            <div class="alert alert-danger">
                                @foreach($errors->all() as $error)
                                {{$error}}
                                @endforeach

                            </div>
                            @endif
                                        <div class="card-title">
                                            <h3 class="text-center">Mugallym üçin täze sapak</h3>
                                        </div>
                                        <hr>
                                        <form action="{{route('teacher_time_table.store')}}" method="POST" enctype="multipart/form-data">
                                           @csrf
                                             
                                            <div class="form-group">
                                                <label  class="control-label mb-1">Gün</label>
                                                <input  name="day" type="number" class="form-control" required >
                                            </div>

                                            <div class="form-group">
                                                <label  class="control-label mb-1">Tertip</label>
                                                <select  name="role" id="category" class="form-control-sm form-control">
                                                            <option  value="sanawjy" >Sanawjy</option>
                                                            <option  value="maydalawjy" >Maýdalawjy</option>
                                                        </select>
                                            </div>

                                             <div class="form-group">
                                                <label  class="control-label mb-1"> Irdenki Wagt</label>
                                                <input  name="time" type="text" class="form-control" required >
                                            </div>

                                            <div class="form-group">
                                                <label  class="control-label mb-1">Öýlänki Wagt</label>
                                                <input  name="afternoon_time" type="text" class="form-control" required >
                                            </div>

                                            <div class="form-group">
                                                <label  class="control-label mb-1"> Auditorýalar</label>
                                                <input  name="auditor" type="text" class="form-control" required >
                                            </div>

                                            <div class="form-group">
                                                <label  class="control-label mb-1">Sapaklar</label>
                                                <input  name="lessons" type="text" class="form-control" required >
                                            </div>

                                            <div class="form-group">
                                                <label  class="control-label mb-1">Sapaklaryň Görnüşleri</label>
                                                <input  name="type_lessons" type="text" class="form-control" required style="text-transform:uppercase" >
                                            </div>
                                        
                                            <div class=" form-group">

                                                <label for="group" class=" form-control-label">Toparlar</label>
                                                <input  name="groups" type="text" class="form-control" required >

                                                </div>

                                            <div class=" form-group">

                                                    <label for="group" class=" form-control-label">Mugallym</label>
                                                        <select name="teacher" id="category" class="form-control-sm form-control">
                                                            @foreach($teachers as $item)
                                                            <option value="{{$item->id}}">{{$item->name}}</option>
                                                            @endforeach
                                                        </select>

                                            </div>                                           
                                             
                                            <div class="text-center">
                                                <button id="payment-button" type="submit" class="btn  btn-success btn-lg">
                                                 Goşmak
                                                </button>
                                            </div>
                                        </form>
                                    </div>
                                </div>

                            </div>
                        </div> <!-- .card -->

                    </div><!--/.col-->
                  </div>
               
@endsection

resources/views/back/teachersSchedule/index.blade.php
@extends('back.layouts.master')
@section('content')
 <div class="content">
            <div class="animated fadeIn">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <a href="{{route('teacher_time_table.create')}}"><div class="btn btn-sm btn-success">+ Mugallym üçin täze sapak</div></a>
                            </div>
                            <div class="table-stats order-table ov-h">
                                <table class="table ">
                                    <thead>
                                        <tr>

                                            <th>Ady</th>
                                            <th>Günler</th>
                                            <th>Tertip</th>
                                            <th>Wagt</th>
                                            <th>Sapaklar</th>
                                            <th>Topar</th>
                                            <th>Goşmaçalar</th>

                                        </tr>
                                    </thead>
                                    <tbody>
                                        
                                        @foreach($time_table as $item)
                                        <tr>
                                        <td> {{ $item->name }} </td>
                                             <td> {{ $item->day }} </td>
                                             <td> {{ $item->role }}   </td>
                                             <td>  <?php $time = json_decode($item->time, true); ?>  {{ $time }} </td>
                                             <td>  <?php $lessons = json_decode($item->lessons, true); ?> {{$lessons}} </td>
                                             <td> {{ $item->group }}  </td>
                                            
                                            
                                             
                                            <td>
                                                <span class="product">
                                                <a href="{{route('teacher_time_table.edit',$item->id)}}" title="Update" class="btn btn-sm btn-primary"><i class="fa fa-pencil-square"></i></a>
                                                 <a href="{{route('teacher_time_tables.delete',$item->id)}}"  title="delete" class="btn btn-sm btn-danger">
                                                   <i class="fa fa-times"></i>
                                                </a>
                                                </span>
                                            </td>
                                        </tr>
                                        @endforeach

                                    </tbody>
                                </table>
                            </div> 
                        </div>
                    </div>
                   
                
               

                
                 
                


           

            

        </div>
    </div><!-- .animated -->
</div><!-- .content -->

@endsection

resources/views/back/teachersSchedule/update.blade.php
@extends('back.layouts.master')
@section('content')


                        <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            
                            <div class="card-body">
                                <!-- Credit Card -->
                                <div id="pay-invoice">
                                    <div class="card-body">
                                        @if($errors->any())
                            <div class="alert alert-danger">
                                @foreach($errors->all() as $error)
                                {{$error}}
                                @endforeach

                            </div>
                            @endif
                                        <div class="card-title">
                                            <h3 class="text-center">Mugallymyň sapaklaryň tertibini redaktirlemek</h3>
                                        </div>
                                        <hr>
                                        <form action="{{route('teacher_time_table.update',$time_table->id)}}" method="POST" enctype="multipart/form-data">
                                         @method('PUT') 
                                             @csrf
                                             
                                             <div class="form-group">
                                                <label  class="control-label mb-1">Gün</label>
                                                <input  name="day" value="{{$time_table->day}}" type="text" class="form-control" required >
                                            </div>
                                                                                     
                                            <div class="form-group">
                                                    <label for="category" class=" form-control-label">Tertip</label>

                                                        <select  name="role" id="category" class="form-control-sm form-control">
                                                            <option @if($time_table->role == 'sanawjy') selected @endif value="sanawjy"> Sanawjy </option>
                                                            <option  @if($time_table->role == 'maydalawjy') selected @endif value="maydalawjy" >Maýdalawjy</option>
                                                        </select>

                                            </div>

                                            <div class="form-group">
                                                <label  class="control-label mb-1"> Irdenki Wagt</label>
                                                <?php $time = json_decode($time_table->time, true); ?> 
                                                <input  name="time" type="text" value="{{$time}}" class="form-control" required >
                                            </div>

                                            <div class="form-group">
                                                <label  class="control-label mb-1"> Öýlänki Wagt</label>
                                                <?php $time_ll = json_decode($time_table->afternoon_time, true); ?> 
                                                <input  name="afternoon_time" type="text" value="{{$time_ll}}" class="form-control" required >
                                            </div>   

                                            <div class="form-group">
                                                <label  class="control-label mb-1"> Auditorýalar</label>
                                                <?php $auditor = json_decode($time_table->auditor, true); ?> 
                                                <input  name="auditor" type="text"  value="{{$auditor}}" class="form-control" required >
                                            </div>
                                            
                                            <div class="form-group">
                                                <label  class="control-label mb-1">Sapaklar</label>
                                                <?php $lessons = json_decode($time_table->lessons, true); ?> 
                                                <input  name="lessons" value="{{$lessons}}"  type="text" class="form-control" required >
                                            </div>

                                            <div class="form-group">
                                                <label  class="control-label mb-1">Sapaklaryň Görnüşleri</label>
                                                <?php $type_lessons = json_decode($time_table->type_lessons, true); ?> 
                                                <input  name="type_lessons" type="text" value="{{$type_lessons}}" class="form-control" required style="text-transform:uppercase" >
                                            </div>

                                            <div class="form-group">
                                                <label  class="control-label mb-1">Toparlar</label>
                                                <?php $groups = json_decode($time_table->group, true); ?> 
                                                <input  name="groups" value="{{$groups}}" type="text" class="form-control" required >
                                            </div>

                                            <div class=" form-group">

                                            <label for="teacher" class=" form-control-label">Mugallym</label>
                                                <select name="teacher" id="category" class="form-control-sm form-control">
                                                    @foreach($teachers as $item)
                                                    <option @if($time_table->teacher_id == $item->id) selected @endif value="{{$item->id}}">{{$item->name}}</option>
                                                    @endforeach
                                                </select>

                                            </div>

                                            <div class="text-center">
                                            <button id="payment-button" type="submit" class="btn  btn-success btn-lg">
                                            Täzele
                                                </button>
                                            </div>
                                        </form>
                                    </div>
                                </div>

                            </div>
                        </div> <!-- .card -->

                    </div><!--/.col-->
                  </div>
@endsection