routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\Api\GroupsController;
use App\Http\Controllers\Api\UsersController;
use App\Http\Controllers\Api\TimeTableController;
use App\Http\Controllers\Api\FacultyController;
use App\Http\Controllers\Api\TeachersController;
use App\Http\Controllers\Api\ScheduleController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('admin')->group(function () {

    Route::resource('groups', GroupsController::class);
    Route::resource('faculty', FacultyController::class);
    Route::get('/faculty/delete/{id}', [FacultyController::class, 'delete'])->name('faculty.delete');
    Route::get('/groupss/delete/{id}', [GroupsController::class, 'delete'])->name('groups.delete');

    Route::resource('users', UsersController::class);
    Route::get('/userss/delete/{id}', [UsersController::class, 'delete'])->name('users.delete');

    Route::resource('teachers', TeachersController::class);
    Route::get('/teachers/delete/{id}', [TeachersController::class, 'delete'])->name('teachers.delete');

    Route::resource('time_table', TimeTableController::class);
    Route::get('/time_tables/delete/{id}', [TimeTableController::class, 'delete'])->name('time_tables.delete');

    Route::resource('teacher_time_table', ScheduleController::class);
    Route::get('/teacher_time_tables/delete/{id}', [ScheduleController::class, 'delete'])->name('teacher_time_tables.delete');

});

app/Http/Controllers/Api/ScheduleController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\TeacherSchedule;
use App\Models\Teacher;
use Illuminate\Support\Facades\DB;
use Validator;

class ScheduleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    { 
        $time_table = DB::table('teacher_schedules')
        ->leftJoin('teachers', 'teachers.id', '=', 'teacher_schedules.teacher_id')
        ->select('teacher_schedules.*', 'teachers.name as name')
        ->orderBy('teacher_schedules.id', 'desc')
        ->get();
       $test = json_decode($time_table, true);
       // dd($test);
        return  view('back.teachersSchedule.index',compact('time_table'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $teachers = DB::table('teachers')
        ->select('teachers.name as name','teachers.id')
        ->orderBy('teachers.id', 'desc')
        ->get();
        return view('back.teachersSchedule.create',compact('teachers'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
            
        $validator = Validator::make(
            $request->all(),
            [ 

            'day' => 'required',
            'role' => 'required',
            'time' => 'required',
            'auditor' => 'required',
            'afternoon_time' => 'required',
            'lessons' => 'required',
            'type_lessons' => 'required',
            'groups' => 'required',
            'teacher' => 'required',

            ]
        );
         
        if ($validator->fails()) {
            return [
                'status' => false,
                'errors' => $validator->messages()
            ];
        }



        $user = new TeacherSchedule;
        $user->day = $request->day;
        $user->role = $request->role;

        $user->time = json_encode($request->time);
        $user->auditor = json_encode($request->auditor);
        $user->afternoon_time = json_encode($request->afternoon_time);
        
        $user->lessons = json_encode($request->lessons);
        $user->type_lessons = json_encode($request->type_lessons);
        
        $user->group = json_encode($request->groups);
        $user->teacher_id = $request->teacher;
        $user->save();

        return redirect()->route('teacher_time_table.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $time_table = TeacherSchedule::findOrFail($id);
        $teachers = Teacher::get();
        return view('back.teachersSchedule.update',compact('time_table','teachers'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make(
            $request->all(),
            [ 

            'day' => 'required',
            'role' => 'required',
            'time' => 'required',
            'auditor' => 'required',
            'afternoon_time' => 'required',
            'lessons' => 'required',
            'type_lessons' => 'required',
            'groups' => 'required',
            'teacher' => 'required',

            ]
        );
         
        if ($validator->fails()) {
            return [
                'status' => false,
                'errors' => $validator->messages()
            ];
        }

        $teacher = TeacherSchedule::findOrFail($id);

        if($teacher == null){
            return redirect()->route('teachersSchedule.index');
        }else{
            $teacher->day = $request->day;
            $teacher->role = $request->role;
    
            $teacher->time = json_encode($request->time);
            $teacher->auditor = json_encode($request->auditor);
            $teacher->afternoon_time = json_encode($request->afternoon_time);
            
            $teacher->lessons = json_encode($request->lessons);
            $teacher->type_lessons = json_encode($request->type_lessons);
            
            $teacher->group = json_encode($request->groups);
            $teacher->teacher_id = $request->teacher;
            $teacher->save();
    
            return redirect()->route('teacher_time_table.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
  
    public function delete($id)
    {
        $group = TeacherSchedule::where('id',$id)->firstOrFail();

            $group->forceDelete();

            return redirect()->route('teacher_time_table.index');
    }
}

resources/views/back/schedule/create.blade.php
@extends('back.layouts.master')
@section('content')


                        <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            
                            <div class="card-body">
                                <!-- Credit Card -->
                                <div id="pay-invoice">
                                    <div class="card-body">
                                        @if($errors->any())
                            <div class="alert alert-danger">
                                @foreach($errors->all() as $error)
                                {{$error}}
                                @endforeach

                            </div>
                            @endif
                                        <div class="card-title">
                                            <h3 class="text-center">Täze Sapak</h3>
                                        </div>
                                        <hr>
                                        <form action="{{route('time_table.store')}}" method="POST" enctype="multipart/form-data">
                                           @csrf
                                             
                                            <div class="form-group">
                                                <label  class="control-label mb-1">Gün</label>
                                                <input  name="day" type="number" class="form-control" required >
                                            </div>

                                            <div class="form-group">
                                                <label  class="control-label mb-1">Tertip</label>
                                                <select  name="role" id="category" class="form-control-sm form-control">
                                                            <option  value="sanawjy" >Sanawjy</option>
                                                            <option  value="maydalawjy" >Maýdalawjy</option>
                                                        </select>
                                            </div>

                                             <div class="form-group">
                                                <label  class="control-label mb-1">Irdenki Wagt</label>
                                                <input  name="time" type="text" class="form-control" required >
                                            </div>

                                            <div class="form-group">
                                                <label  class="control-label mb-1">Öýlänki Wagt</label>
                                                <input  name="afternoon_time" type="text" class="form-control" required >
                                            </div>

                                            <div class="form-group">
                                                <label  class="control-label mb-1"> Auditorýalar</label>
                                                <input  name="auditor" type="text" class="form-control" required >
                                            </div>

                                            <div class="form-group">
                                                <label  class="control-label mb-1">Sapaklar</label>
                                                <input  name="lessons" type="text" class="form-control" required >
                                            </div>

                                            <div class="form-group">
                                                <label  class="control-label mb-1">Sapaklaryň Görnüşleri</label>
                                                <input  name="type_lessons" type="text" class="form-control" required style="text-transform:uppercase" >
                                            </div>

                                            <div class="form-group">
                                                <label  class="control-label mb-1">Mugallymlar</label>
                                                <input  name="teachers" type="text" class="form-control" required >
                                            </div>

                                           

                                            <div class=" form-group">

                                                    <label for="group" class=" form-control-label">Toparlar</label>
                                                        <select name="group" id="category" class="form-control-sm form-control">
                                                            @foreach($groups as $item)
                                                            <option value="{{$item->id}}">{{$item->group}}</option>
                                                            @endforeach
                                                        </select>

                                            </div>
                                           
                                            <div class="text-center">
                                                <button id="payment-button" type="submit" class="btn  btn-success btn-lg">
                                                 Goşmak
                                                </button>
                                            </div>
                                        </form>
                                    </div>
                                </div>

                            </div>
                        </div> <!-- .card -->

                    </div><!--/.col-->
                  </div>
               
@endsection

resources/views/back/schedule/index.blade.php
@extends('back.layouts.master')
@section('content')
 <div class="content">
            <div class="animated fadeIn">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <a href="{{route('time_table.create')}}"><div class="btn btn-sm btn-success">+ Täze Sapak</div></a>
                            </div>
                            <div class="table-stats order-table ov-h">
                                <table class="table ">
                                    <thead>
                                        <tr>
                                         
                                            <th>Günler</th>
                                            <th>Tertip</th>
                                            <th>Wagt</th>
                                            <th>Sapaklar</th>
                                            <th>Mugallymlar</th>
                                            <th>Topar nomer</th>
                                            <th>Goşmaçalar</th>

                                        </tr>
                                    </thead>
                                    <tbody>
                                        
                                        @foreach($time_table as $item)
                                        <tr>
                                        
                                             <td> {{ $item->day }} </td>
                                             <td> {{ $item->role }}   </td>
                                             <td>  <?php $time = json_decode($item->time, true); ?>  {{ $time }} </td>
                                             <td>  <?php $lessons = json_decode($item->lessons, true); ?> {{$lessons}} </td>
                                             <td>  <?php $teachers = json_decode($item->teachers, true); ?>{{ $teachers }}  </td>
                                             <td> {{ $item->group }}  </td>
                                            
                                            
                                             
                                            <td>
                                                <span class="product">
                                                <a href="{{route('time_table.edit',$item->id)}}" title="Update" class="btn btn-sm btn-primary"><i class="fa fa-pencil-square"></i></a>
                                                 <a href="/admin/time_tables/delete/{{$item->id}}"  title="delete" class="btn btn-sm btn-danger">
                                                   <i class="fa fa-times"></i>
                                                </a>
                                                </span>
                                            </td>
                                        </tr>
                                        @endforeach

                                    </tbody>
                                </table>
                            </div> 
                        </div>
                    </div>
                   
                
               

                
                 
                


           

            

        </div>
    </div><!-- .animated -->
</div><!-- .content -->

@endsection

resources/views/back/schedule/update.blade.php
@extends('back.layouts.master')
@section('content')


                        <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            
                            <div class="card-body">
                                <!-- Credit Card -->
                                <div id="pay-invoice">
                                    <div class="card-body">
                                        @if($errors->any())
                            <div class="alert alert-danger">
                                @foreach($errors->all() as $error)
                                {{$error}}
                                @endforeach

                            </div>
                            @endif
                                        <div class="card-title">
                                            <h3 class="text-center">Sapaklary redaktirläň</h3>
                                        </div>
                                        <hr>
                                        <form action="{{route('time_table.update',$time_table->id)}}" method="POST" enctype="multipart/form-data">
                                         @method('PUT') 
                                             @csrf
                                             
                                             <div class="form-group">
                                                <label  class="control-label mb-1">Gün</label>
                                                <input  name="day" value="{{$time_table->day}}" type="text" class="form-control" required >
                                            </div>
                                                                                     
                                            <div class="form-group">
                                                    <label for="category" class=" form-control-label">Tertip</label>

                                                        <select  name="role" id="category" class="form-control-sm form-control">
                                                            <option @if($time_table->role == 'sanawjy') selected @endif value="sanawjy"> Sanawjy </option>
                                                            <option  @if($time_table->role == 'maydalawjy') selected @endif value="maydalawjy" >Maýdalawjy</option>
                                                        </select>

                                            </div>

                                            <div class="form-group">
                                                <label  class="control-label mb-1">Irdenki Wagt</label>
                                                <?php $time = json_decode($time_table->time, true); ?> 
                                                <input  name="time" type="text" value="{{$time}}" class="form-control" required >
                                            </div>

                                            <div class="form-group">
                                                <label  class="control-label mb-1">Öýlänki Wagt</label>
                                                <?php $time_ll = json_decode($time_table->afternoon_time, true); ?> 
                                                <input  name="afternoon_time" type="text" value="{{$time_ll}}" class="form-control" required >
                                            </div>

                                            <div class="form-group">
                                                <label  class="control-label mb-1"> Auditorýalar </label>
                                                <?php $auditor = json_decode($time_table->auditor, true); ?> 
                                                <input  name="auditor" type="text"  value="{{$auditor}}" class="form-control" required >
                                            </div>
                                            
                                            <div class="form-group">
                                                <label  class="control-label mb-1">Sapaklar</label>
                                                <?php $lessons = json_decode($time_table->lessons, true); ?> 
                                                <input  name="lessons" value="{{$lessons}}"  type="text" class="form-control" required >
                                            </div>

                                            <div class="form-group">
                                                <label  class="control-label mb-1">Sapaklaryň Görnüşleri</label>
                                                <?php $type_lessons = json_decode($time_table->type_lessons, true); ?> 
                                                <input  name="type_lessons" type="text" value="{{$type_lessons}}" class="form-control" required style="text-transform:uppercase" >
                                            </div>

                                            <div class="form-group">
                                                <label  class="control-label mb-1">Mugallymlar</label>
                                                <?php $teachers = json_decode($time_table->teachers, true); ?> 
                                                <input  name="teachers" value="{{$teachers}}" type="text" class="form-control" required >
                                            </div>

                                            <div class=" form-group">

                                                    <label for="group" class=" form-control-label">Topary</label>
                                                        <select name="group" id="category" class="form-control-sm form-control">
                                                            @foreach($groups as $item)
                                                            <option @if($time_table->group_id == $item->id) selected @endif value="{{$item->id}}">{{$item->group_number}}</option>
                                                            @endforeach
                                                        </select>

                                            </div>

                                            <div class="text-center">
                                            <button id="payment-button" type="submit" class="btn  btn-success btn-lg">
                                            Täzele
                                                </button>
                                            </div>
                                        </form>
                                    </div>
                                </div>

                            </div>
                        </div> <!-- .card -->

                    </div><!--/.col-->
                  </div>
@endsection